### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by arminius2** [natanweinberger/smartrent-python#1]
Been trying to get this to run in my python environment and haven't been very successful - wondering if they've changed their API to make this code not work?

**Comment by natanweinberger** [comment]
Hey! Sorry I didn't see the notification for this before 😬

I'd like to take a look at it, but I don't have an active account with Smartrent anymore since I've moved to a new place. If you want to work together, I could try troubleshooting it with you if you have an account with them.

Wouldn't be shocked if they've changed the API though. They were in the process of developing a v2 of their API when I was working on this.

At the time, v1 and v2 were both partially in use, one of them for auth endpoints and the other for the rest of the endpoints. You can see [here]( https://github.com/natanweinberger/smartrent-python/blob/prod/smartrent_python/api.py#L12-L13) where I set up something to handle accessing both.

**Comment by arminius2** [comment]
That would be rad. I’d appreciate your help getting spun up.  Then I’d love to build off your work.

**Comment by natanweinberger** [comment]
Cool, probably easiest on my end if I can take a look at what's coming back from their API in real time. Wanna set up a time to chat and you can show me what it's looking like? My email is in the Docker file, reach out there and we'll find a time.

Glad to see this might be useful for someone else 🙂

**Comment by natanweinberger** [comment]
Hey @arminius2, I just spun this up locally and saw a couple bugs I never fixed. I just patched them, give it another shot when you have a chance.
